Add Extract and Upload Defconfig Change default branch and Optimized code

diff --git a/.github/workflows/bulid-kernel_ksu patch lineage.yml b/.github/workflows/bulid-kernel_ksu patch lineage.yml
--- a/.github/workflows/bulid-kernel_ksu patch lineage.yml
+++ b/.github/workflows/bulid-kernel_ksu patch lineage.yml
@@ -1,4 +1,4 @@
-name: Build Kernel_diff patch rcmiku
+name: Build Kernel_diff patch lineage
 
 on:
   workflow_dispatch:
@@ -10,17 +10,17 @@ on:
       KERNEL_SOURCE_BRANCH:
         description: 'Branch'
         required: true
-        default: 'aries'
+        default: 'lineage-22.1'
       KERNEL_DEFCONFIG:
         description: 'Defconfig'
         required: true
         default: 'alioth_defconfig'
       AOSP_CLANG_BRANCH:
-        description: 'AOSP Clang branch'
+        description: 'AOSP Clang Branch'
         required: true
         default: 'main'
       AOSP_CLANG_VERSION:
-        description: 'AOSP Clang version'
+        description: 'AOSP Clang Version'
         required: true
         default: 'r530567'
       USE_CUSTOM_CLANG:
@@ -41,16 +41,16 @@ on:
         required: true
         default: true
         type: boolean
+      ADD_PATH_UMOUNT:
+        description: 'Add `path_umount` for KernelSU'
+        required: true
+        default: true
+        type: boolean
       ENABLE_KERNELSU_DEBUG:
         description: 'Use KernelSU Debug'
         required: true
         default: false
         type: boolean
-      ADD_PATH_UMOUNT:
-        description: 'Add `path_umount` for KernelSU'
-        required: true
-        default: true
-        type: boolean      
 
 jobs:
   build:
@@ -107,8 +107,8 @@ jobs:
         cd kernel-source
         export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
         chmod +x scripts/update_defconfig
-        ./scripts/update_defconfig alioth
-        echo "[+] Update Defconfig"
+        ./scripts/update_defconfig ${{ env.DEVICE }}
+        echo "[+] Update Defconfig Successful"
 
     - name: Setup KernelSU
       if: env.ENABLE_KERNELSU == 'true'
@@ -119,13 +119,13 @@ jobs:
         git am ../patch/KernelSU.patch
         echo "CONFIG_KSU=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
         curl -LSs "https://raw.githubusercontent.com/sakana164/KernelSU/non-gki/kernel/setup.sh" | bash -s non-gki
-        echo "ENABLE_KERNELSU=-KernelSU" >> $GITHUB_ENV
         if [ ${{ env.ENABLE_KERNELSU_DEBUG }} = true ]; then
           echo "CONFIG_KSU_DEBUG=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
         fi
         if [ ${{ env.ADD_PATH_UMOUNT }} = true ]; then
           git am ../patch/KernelSU-path_umount.patch
         fi
+        git submodule add https://github.com/sakana164/KernelSU.git KernelSU
         echo "[+] KernelSU setup done."
 
     - name: Make working directory clean to avoid dirty
@@ -133,8 +133,7 @@ jobs:
         cd kernel-source
         git config user.name "GitHub Actions"
         git config user.email "actions@github.com"
-        git submodule add https://github.com/sakana164/KernelSU.git KernelSU
-        git add -A && git commit -am "Make working directory clean succeed" || echo "Commit failed,No changes to commit"
+        git add -A && git commit -am "Make working directory clean done" || echo "Commit failed,No changes to commit"
 
     - name: Build Kernel
       run: |
@@ -175,6 +174,12 @@ jobs:
         cp out/arch/arm64/boot/Image AnyKernel3
         cp out/arch/arm64/boot/dtbo.img AnyKernel3
         cp out/arch/arm64/boot/dtb AnyKernel3
+        ./scripts/extract-ikconfig out/arch/arm64/boot/Image > ${{ env.KERNEL_DEFCONFIG }}-${{ env.BUILD_TIME }}
+        if [ "${{ env.ENABLE_KERNELSU }}" = "true" ]; then
+          echo "ENABLE_KERNELSU=-KernelSU" >> $GITHUB_ENV
+        else
+          echo "ENABLE_KERNELSU=" >> $GITHUB_ENV
+        fi
 
     - name: Upload Kernel
       uses: actions/upload-artifact@v4
@@ -188,3 +193,9 @@ jobs:
           !kernel-source/AnyKernel3/ramdisk
           !kernel-source/AnyKernel3/README.md
         compression-level: 9
+
+    - name: Upload Defconfig
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ env.KERNEL_SOURCE_BRANCH }}-${{ env.KERNEL_DEFCONFIG }}-${{ env.BUILD_TIME }}
+        path: kernel-source/${{ env.KERNEL_DEFCONFIG }}-${{ env.BUILD_TIME }}
